- hosts: esnode1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      node.name: "esnode1"
      cluster.initial_master_nodes: "esnode1,esnode2,esnode3"
      discovery.seed_hosts: "esnode1:9300,esnode2:9300,esnode3:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
      xpack.security.authc.realms.file.file1.order: 0
      xpack.security.authc.realms.native.native1.order: 1
    es_api_basic_auth_username: "elastic" # This is the default user created by the installation of elasticsearch
    es_api_basic_auth_password: "changeme" # This is the default password created by the installation of elasticsearch
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_ssl_keystore: "files/certs/my-keystore.p12"
    es_ssl_truststore: "files/certs/my-ca.p12"
    es_ssl_keystore_password: "keystore_password"
    es_ssl_truststore_password: "ca_password"
    es_validate_certs: no


- hosts: esnode2
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      node.name: "esnode2"
      cluster.initial_master_nodes: "esnode1,esnode2,esnode3"
      discovery.seed_hosts: "esnode1:9300,esnode2:9300,esnode3:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
      xpack.security.authc.realms.file.file1.order: 0
      xpack.security.authc.realms.native.native1.order: 1
    es_api_basic_auth_username: "elastic" # This is the default user created by the installation of elasticsearch
    es_api_basic_auth_password: "changeme" # This is the default password created by the installation of elasticsearch
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_ssl_keystore: "files/certs/my-keystore.p12"
    es_ssl_truststore: "files/certs/my-ca.p12"
    es_ssl_keystore_password: "keystore_password"
    es_ssl_truststore_password: "ca_password"
    es_validate_certs: no


- hosts: esnode3
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_heap_size: "1g"
    es_config:
      cluster.name: "test-cluster"
      node.name: "esnode3"
      cluster.initial_master_nodes: "esnode1,esnode2,esnode3"
      discovery.seed_hosts: "esnode1:9300,esnode2:9300,esnode3:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
      xpack.security.authc.realms.file.file1.order: 0
      xpack.security.authc.realms.native.native1.order: 1
    es_api_basic_auth_username: "elastic" # This is the default user created by the installation of elasticsearch
    es_api_basic_auth_password: "changeme" # This is the default password created by the installation of elasticsearch
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_ssl_keystore: "files/certs/my-keystore.p12"
    es_ssl_truststore: "files/certs/my-ca.p12"
    es_ssl_keystore_password: "keystore_password"
    es_ssl_truststore_password: "ca_password"
    es_validate_certs: no
